//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Icebreaker.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Icebreaker.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to edit team settings.
        /// </summary>
        internal static string AdminActionEditTeamSettings {
            get {
                return ResourceManager.GetString("AdminActionEditTeamSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to edit user.
        /// </summary>
        internal static string AdminActionEditUser {
            get {
                return ResourceManager.GetString("AdminActionEditUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to generate pairs.
        /// </summary>
        internal static string AdminActionGeneratePairs {
            get {
                return ResourceManager.GetString("AdminActionGeneratePairs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} action is only for users who have admin privileges..
        /// </summary>
        internal static string AdminActionNoTeamMsg {
            get {
                return ResourceManager.GetString("AdminActionNoTeamMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to change notify mode to require admin approval.
        /// </summary>
        internal static string AdminActionNotifyNeedApproval {
            get {
                return ResourceManager.GetString("AdminActionNotifyNeedApproval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to change notify mode to no approval.
        /// </summary>
        internal static string AdminActionNotifyNoApproval {
            get {
                return ResourceManager.GetString("AdminActionNotifyNoApproval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Which team do you wish to {0} for?.
        /// </summary>
        internal static string AdminActionWhichTeamText {
            get {
                return ResourceManager.GetString("AdminActionWhichTeamText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat with {0}.
        /// </summary>
        internal static string ChatWithMatchButtonText {
            get {
                return ResourceManager.GetString("ChatWithMatchButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat With Me.
        /// </summary>
        internal static string ChatWithMeButtonText {
            get {
                return ResourceManager.GetString("ChatWithMeButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Enrollment.
        /// </summary>
        internal static string EditEnrollmentButtonText {
            get {
                return ResourceManager.GetString("EditEnrollmentButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Profile .
        /// </summary>
        internal static string EditProfileButtonText {
            get {
                return ResourceManager.GetString("EditProfileButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin: Edit Team Settings.
        /// </summary>
        internal static string EditTeamSettingsButtonText {
            get {
                return ResourceManager.GetString("EditTeamSettingsButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin: Edit Any User.
        /// </summary>
        internal static string EditUserButtonText {
            get {
                return ResourceManager.GetString("EditUserButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error while processing the request. Retry?.
        /// </summary>
        internal static string ErrorOccured {
            get {
                return ResourceManager.GetString("ErrorOccured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you eat lunch? Why not do it with a buddy? I can match you with someone new each month so you can meet new friends or just get to know your team better..
        /// </summary>
        internal static string InstallMessageBotDescription {
            get {
                return ResourceManager.GetString("InstallMessageBotDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to **Join in and I will message you at the start of the month with your match.**.
        /// </summary>
        internal static string InstallMessageInstruction {
            get {
                return ResourceManager.GetString("InstallMessageInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to **Admin Instructions**.
        /// </summary>
        internal static string InstallMessageInstructionAdmin {
            get {
                return ResourceManager.GetString("InstallMessageInstructionAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you&apos;re reading this, it&apos;s most likely because {0} added me to the **{1}** team..
        /// </summary>
        internal static string InstallMessageKnownInstaller {
            get {
                return ResourceManager.GetString("InstallMessageKnownInstaller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit your profile to ensure a good match. You can always pause matches at any time. .
        /// </summary>
        internal static string InstallMessageSuggestedNextStep {
            get {
                return ResourceManager.GetString("InstallMessageSuggestedNextStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. Edit the team settings to setup the subteam names.\r2. Send the welcome team card to the team. (New members added to the team will get a welcome message automatically).\r3. Join LunchBuddy and edit your profile to ensure a good match.\r4. Wait for a match at the beginning of the month or you can click {0} to create matches right away (you will have the ability to review them before deciding to send it)..
        /// </summary>
        internal static string InstallMessageSuggestedNextStepAdmin {
            get {
                return ResourceManager.GetString("InstallMessageSuggestedNextStepAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you&apos;re reading this, it&apos;s because I was installed to **{0}** team..
        /// </summary>
        internal static string InstallMessageUnknownInstaller {
            get {
                return ResourceManager.GetString("InstallMessageUnknownInstaller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join LunchBuddy in {0}.
        /// </summary>
        internal static string JoinButtonText {
            get {
                return ResourceManager.GetString("JoinButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin: Create Pairs.
        /// </summary>
        internal static string MakePairsButtonText {
            get {
                return ResourceManager.GetString("MakePairsButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not notify the users. Please try again or regenerate new pairings..
        /// </summary>
        internal static string ManualNotifiedUsersErrorMessage {
            get {
                return ResourceManager.GetString("ManualNotifiedUsersErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notified {0} pair(s)..
        /// </summary>
        internal static string ManualNotifiedUsersMessage {
            get {
                return ResourceManager.GetString("ManualNotifiedUsersMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi there again, I&apos;m {0} in {1}. A bot that pairs you with a new coworker to meet each month..
        /// </summary>
        internal static string MatchUpCardContentPart1 {
            get {
                return ResourceManager.GetString("MatchUpCardContentPart1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feel free to set something up :).
        /// </summary>
        internal static string MatchUpCardContentPart2 {
            get {
                return ResourceManager.GetString("MatchUpCardContentPart2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve been matched with **{0}**..
        /// </summary>
        internal static string MatchUpCardMatchedText {
            get {
                return ResourceManager.GetString("MatchUpCardMatchedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It&apos;s time for a match!.
        /// </summary>
        internal static string MatchUpCardTitleContent {
            get {
                return ResourceManager.GetString("MatchUpCardTitleContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hey there, looks like we&apos;ve been matched by {0} this month. It would be great to meet up for a lunch or a chat if you&apos;ve got time..
        /// </summary>
        internal static string MeetupContent {
            get {
                return ResourceManager.GetString("MeetupContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} / {1} LunchBuddy.
        /// </summary>
        internal static string MeetupTitle {
            get {
                return ResourceManager.GetString("MeetupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have received this message because you are the admin designated for approving new pairings for the team.&lt;br/&gt;Send the pairings if it looks good, or you may create new pairings..
        /// </summary>
        internal static string NewPairingsDescription {
            get {
                return ResourceManager.GetString("NewPairingsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are not enough active users to make pairs. You need at least two but there are currently {0}..
        /// </summary>
        internal static string NewPairingsNotEnoughUsers {
            get {
                return ResourceManager.GetString("NewPairingsNotEnoughUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odd Person.
        /// </summary>
        internal static string NewPairingsOddPerson {
            get {
                return ResourceManager.GetString("NewPairingsOddPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Pairings for {0}.
        /// </summary>
        internal static string NewPairingsTitle {
            get {
                return ResourceManager.GetString("NewPairingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry I had a problem updating the notify mode..
        /// </summary>
        internal static string NotifyModeFail {
            get {
                return ResourceManager.GetString("NotifyModeFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matches will be sent to the admin for approval before the users are notified of their pairing..
        /// </summary>
        internal static string NotifyModeNeedApprovalSuccess {
            get {
                return ResourceManager.GetString("NotifyModeNeedApprovalSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matches will be sent to the pairs without asking for admin approval..
        /// </summary>
        internal static string NotifyModeNoApprovalSuccess {
            get {
                return ResourceManager.GetString("NotifyModeNoApprovalSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome {0}! When match time occurs, I will message you with your new buddy. (This only occurs for people in the team.).
        /// </summary>
        internal static string OptInConfirmation {
            get {
                return ResourceManager.GetString("OptInConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, I had trouble opting you back in. Retry?.
        /// </summary>
        internal static string OptInUserFailText {
            get {
                return ResourceManager.GetString("OptInUserFailText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;ve paused your matches in {0}. You can turn them back on whenever you like..
        /// </summary>
        internal static string OptOutConfirmation {
            get {
                return ResourceManager.GetString("OptOutConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;ve paused {0}&apos;s matches in {1}. You can turn them back on whenever you like..
        /// </summary>
        internal static string OptOutConfirmationAnotherUser {
            get {
                return ResourceManager.GetString("OptOutConfirmationAnotherUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, I had trouble opting you out. Retry?.
        /// </summary>
        internal static string OptOutUserFailText {
            get {
                return ResourceManager.GetString("OptOutUserFailText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause Matches in {0}.
        /// </summary>
        internal static string PausePairingsButtonText {
            get {
                return ResourceManager.GetString("PausePairingsButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Propose Meetup.
        /// </summary>
        internal static string ProposeMeetupButtonText {
            get {
                return ResourceManager.GetString("ProposeMeetupButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Pairings.
        /// </summary>
        internal static string RegeneratePairingsButtonText {
            get {
                return ResourceManager.GetString("RegeneratePairingsButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resume Matches in {0}.
        /// </summary>
        internal static string ResumePairingsButtonText {
            get {
                return ResourceManager.GetString("ResumePairingsButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi there!.
        /// </summary>
        internal static string SalutationTitleText {
            get {
                return ResourceManager.GetString("SalutationTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, I could not save the user profile. Retry?.
        /// </summary>
        internal static string SaveProfileFailText {
            get {
                return ResourceManager.GetString("SaveProfileFailText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, I could not save the user info. Retry?.
        /// </summary>
        internal static string SaveUserInfoFailText {
            get {
                return ResourceManager.GetString("SaveUserInfoFailText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Pairings.
        /// </summary>
        internal static string SendPairingsButtonText {
            get {
                return ResourceManager.GetString("SendPairingsButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I had trouble sending the welcome card to {0}. Retry?.
        /// </summary>
        internal static string SendWelcomeCardFail {
            get {
                return ResourceManager.GetString("SendWelcomeCardFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sent welcome card to {0}.
        /// </summary>
        internal static string SendWelcomeCardSuccess {
            get {
                return ResourceManager.GetString("SendWelcomeCardSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take a Tour.
        /// </summary>
        internal static string TakeATourButtonText {
            get {
                return ResourceManager.GetString("TakeATourButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unknown.
        /// </summary>
        internal static string UnknownUserName {
            get {
                return ResourceManager.GetString("UnknownUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi! What would you like to do?.
        /// </summary>
        internal static string UnrecognizedInput {
            get {
                return ResourceManager.GetString("UnrecognizedInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin: Send Welcome Card.
        /// </summary>
        internal static string WelcomeTeamButtonText {
            get {
                return ResourceManager.GetString("WelcomeTeamButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat with me to join in. You can always pause matches at any time..
        /// </summary>
        internal static string WelcomeTeamSuggestedNextStep {
            get {
                return ResourceManager.GetString("WelcomeTeamSuggestedNextStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tour.
        /// </summary>
        internal static string WelcomeTourTitle {
            get {
                return ResourceManager.GetString("WelcomeTourTitle", resourceCulture);
            }
        }
    }
}
