//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Icebreaker.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Icebreaker.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to edit team settings.
        /// </summary>
        internal static string AdminActionEditTeamSettings {
            get {
                return ResourceManager.GetString("AdminActionEditTeamSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to generate pairs.
        /// </summary>
        internal static string AdminActionGeneratePairs {
            get {
                return ResourceManager.GetString("AdminActionGeneratePairs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} action is only for users who have admin privileges..
        /// </summary>
        internal static string AdminActionNoTeamMsg {
            get {
                return ResourceManager.GetString("AdminActionNoTeamMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to change notify mode to require admin approval.
        /// </summary>
        internal static string AdminActionNotifyNeedApproval {
            get {
                return ResourceManager.GetString("AdminActionNotifyNeedApproval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to change notify mode to no approval.
        /// </summary>
        internal static string AdminActionNotifyNoApproval {
            get {
                return ResourceManager.GetString("AdminActionNotifyNoApproval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Which team do you wish to {0} for?.
        /// </summary>
        internal static string AdminActionWhichTeamText {
            get {
                return ResourceManager.GetString("AdminActionWhichTeamText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat with {0}.
        /// </summary>
        internal static string ChatWithMatchButtonText {
            get {
                return ResourceManager.GetString("ChatWithMatchButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Profile .
        /// </summary>
        internal static string EditProfileButtonText {
            get {
                return ResourceManager.GetString("EditProfileButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error while processing request. Retry?.
        /// </summary>
        internal static string ErrorOccured {
            get {
                return ResourceManager.GetString("ErrorOccured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you&apos;re reading this, it&apos;s most likely because {0} added me to the **{1} Team.**.
        /// </summary>
        internal static string InstallMessageKnownInstallerPart1 {
            get {
                return ResourceManager.GetString("InstallMessageKnownInstallerPart1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I get to help you meet more people around your organization by randomly pairing you with someone new every month. You get to make more friends and learn about the people you work with..
        /// </summary>
        internal static string InstallMessageKnownInstallerPart2 {
            get {
                return ResourceManager.GetString("InstallMessageKnownInstallerPart2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to **To meet new people, just hang tight. I&apos;ll send you an invite when a new month starts.**.
        /// </summary>
        internal static string InstallMessageKnownInstallerPart3 {
            get {
                return ResourceManager.GetString("InstallMessageKnownInstallerPart3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you&apos;re reading this, it&apos;s because I was installed to **{0} Team.** .
        /// </summary>
        internal static string InstallMessageUnknownInstallerPart1 {
            get {
                return ResourceManager.GetString("InstallMessageUnknownInstallerPart1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I get to help you meet more people around your organization by randomly pairing you with someone new every month. You get to make more friends and learn about the people you work with..
        /// </summary>
        internal static string InstallMessageUnknownInstallerPart2 {
            get {
                return ResourceManager.GetString("InstallMessageUnknownInstallerPart2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to **To meet new people, just hang tight. I&apos;ll send you an invite when a new month starts.**.
        /// </summary>
        internal static string InstallMessageUnknownInstallerPart3 {
            get {
                return ResourceManager.GetString("InstallMessageUnknownInstallerPart3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not notify the users. Please try again or regenerate new pairings..
        /// </summary>
        internal static string ManualNotifiedUsersErrorMessage {
            get {
                return ResourceManager.GetString("ManualNotifiedUsersErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notified {0} pair(s)..
        /// </summary>
        internal static string ManualNotifiedUsersMessage {
            get {
                return ResourceManager.GetString("ManualNotifiedUsersMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi there again, I&apos;m {0} in {1}. A bot that pairs you with a new coworker to meet each month..
        /// </summary>
        internal static string MatchUpCardContentPart1 {
            get {
                return ResourceManager.GetString("MatchUpCardContentPart1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feel free to set something up :).
        /// </summary>
        internal static string MatchUpCardContentPart2 {
            get {
                return ResourceManager.GetString("MatchUpCardContentPart2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve been matched with **{0}**..
        /// </summary>
        internal static string MatchUpCardMatchedText {
            get {
                return ResourceManager.GetString("MatchUpCardMatchedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It&apos;s time for a match!.
        /// </summary>
        internal static string MatchUpCardTitleContent {
            get {
                return ResourceManager.GetString("MatchUpCardTitleContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hey there, looks like we&apos;ve been matched by {0} this month. It&apos;d be great to meet up for a coffee or a lunch or a call if you&apos;ve got time..
        /// </summary>
        internal static string MeetupContent {
            get {
                return ResourceManager.GetString("MeetupContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} / {1} LunchBuddy.
        /// </summary>
        internal static string MeetupTitle {
            get {
                return ResourceManager.GetString("MeetupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have received this message because you are the admin designated for approving new pairings for the team.&lt;br/&gt;Send the pairings if it looks good, or you may create new pairings..
        /// </summary>
        internal static string NewPairingsDescription {
            get {
                return ResourceManager.GetString("NewPairingsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odd Person.
        /// </summary>
        internal static string NewPairingsOddPerson {
            get {
                return ResourceManager.GetString("NewPairingsOddPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Pairings for {0}.
        /// </summary>
        internal static string NewPairingsTitle {
            get {
                return ResourceManager.GetString("NewPairingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry I had a problem updating the notify mode..
        /// </summary>
        internal static string NotifyModeFail {
            get {
                return ResourceManager.GetString("NotifyModeFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matches will be sent to the admin for approval before the users are notified of their pairing..
        /// </summary>
        internal static string NotifyModeNeedApprovalSuccess {
            get {
                return ResourceManager.GetString("NotifyModeNeedApprovalSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matches will be sent to the pairs without asking for admin approval..
        /// </summary>
        internal static string NotifyModeNoApprovalSuccess {
            get {
                return ResourceManager.GetString("NotifyModeNoApprovalSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome back! You&apos;ve been missed. I&apos;ve restarted your matches. Have fun!.
        /// </summary>
        internal static string OptInConfirmation {
            get {
                return ResourceManager.GetString("OptInConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, I had trouble opting you back in. Please make sure you are connected to the internet. .
        /// </summary>
        internal static string OptInUserFailText {
            get {
                return ResourceManager.GetString("OptInUserFailText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All set. I&apos;ve paused your matches. You can turn them back on whenever you like..
        /// </summary>
        internal static string OptOutConfirmation {
            get {
                return ResourceManager.GetString("OptOutConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, I had trouble opting you out. Please make sure you are connected to the internet. .
        /// </summary>
        internal static string OptOutUserFailText {
            get {
                return ResourceManager.GetString("OptOutUserFailText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause all matches.
        /// </summary>
        internal static string PausePairingsButtonText {
            get {
                return ResourceManager.GetString("PausePairingsButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Propose meetup.
        /// </summary>
        internal static string ProposeMeetupButtonText {
            get {
                return ResourceManager.GetString("ProposeMeetupButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Pairings.
        /// </summary>
        internal static string RegeneratePairingsButtonText {
            get {
                return ResourceManager.GetString("RegeneratePairingsButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resume matches.
        /// </summary>
        internal static string ResumePairingsButtonText {
            get {
                return ResourceManager.GetString("ResumePairingsButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi there!.
        /// </summary>
        internal static string SalutationTitleText {
            get {
                return ResourceManager.GetString("SalutationTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, I could not save the user profile. Please make sure you are connected to the internet..
        /// </summary>
        internal static string SaveProfileFailText {
            get {
                return ResourceManager.GetString("SaveProfileFailText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Pairings.
        /// </summary>
        internal static string SendPairingsButtonText {
            get {
                return ResourceManager.GetString("SendPairingsButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take a tour.
        /// </summary>
        internal static string TakeATourButtonText {
            get {
                return ResourceManager.GetString("TakeATourButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m sorry, but I can&apos;t process the incoming message. You can take a tour, though, to learn more about my functionality..
        /// </summary>
        internal static string UnrecognizedInput {
            get {
                return ResourceManager.GetString("UnrecognizedInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tour.
        /// </summary>
        internal static string WelcomeTourTitle {
            get {
                return ResourceManager.GetString("WelcomeTourTitle", resourceCulture);
            }
        }
    }
}
